### ISSUE TITLE
[WIP] Advanced ANTLR Grammar (Remove "" and [], better token recognition)

### ISSUE THREAD

**Issue by ExVacuum** [Java-prog-class-2019/slate#3]
@ExVacuum needs to enhance the grammar token recognition in order to make things look prettier for the user. 
e.g. 
say "Hello!" 
will be changed to
say Hello!

Likely all I will need to do is modify the order in which the lexer rules are set.

**Comment by Ewpratten** [comment]
I would like to propose a slight design change. 

To keep the code a little cleaner, it may be a good idea to modify `Commands.parseCommand()` to return a `Command` object.

`Command` prototype:
```java
class Command {
    int type;
    String[] context;
}
```

The `type` would be one of the commands from the `SlateParser` class. This would allow us to move the **switch/case** statement elsewhere in the code, and the `context` would be a list of all "things" that the user enters after the command. 

For example, `say "hello"` would result in the following:
```java
class Command {
    int type = SlateParser.SAY;
    String[] context = {"hello"};
}
```

**Comment by ExVacuum** [comment]
Alright, I agree that a `Command` object would definitely be cleaner. In this case, it would probably also be a good idea to create an `execute()` method inside of the class. The switch, as well as context validation, can go there to remove clutter from the `Commands` class. I also want to find a way to remove the need for a switch statement anyways.
